// GSMAXALL Unified AI Gateway & Model Router

export interface RouterConfig {
  model: string;
  prompt: string;
  history?: Array<{ role: string; content: string }>;
  temperature?: number;
}

export interface RouterResponse {
  reply: string;
  modelUsed: string;
  costEstimate: number; // in USD
  latencyMs: number;
}

const COST_METRICS: Record<string, { prompt: number, completion: number }> = {
  "gpt-4o": { prompt: 0.000005, completion: 0.000015 },
  "claude-3-5-sonnet": { prompt: 0.000003, completion: 0.000015 },
  "gemini-1-5-pro": { prompt: 0.00000125, completion: 0.00000375 },
  "deepseek-v3": { prompt: 0.00000014, completion: 0.00000028 }
};

export class AiGateway {
  /**
   * Route prompts with automatic fallback strategies
   */
  static async generate(config: RouterConfig): Promise<RouterResponse> {
    const startTime = Date.now();
    const modelChain = this.getFallbackChain(config.model);
    
    let errorLog = [];
    
    // Try models sequentially (fallback routing)
    for (const activeModel of modelChain) {
      try {
        const hasKey = this.verifyProviderKey(activeModel);
        if (!hasKey) {
          throw new Error(`Key missing for model provider: ${activeModel}`);
        }

        // Mock call simulation representing successful external api request
        const delay = Math.floor(Math.random() * 200) + 100;
        await new Promise(r => setTimeout(r, delay));
        
        const reply = this.getMockResponse(activeModel, config.prompt);
        const latencyMs = Date.now() - startTime;
        const costEstimate = this.calculateCost(activeModel, config.prompt.length, reply.length);
        
        return {
          reply,
          modelUsed: activeModel,
          costEstimate,
          latencyMs
        };
      } catch (err: any) {
        errorLog.push(`${activeModel}: ${err.message}`);
        console.warn(`[AI Gateway Fallback] failing over from ${activeModel}: ${err.message}`);
      }
    }

    // Default ultimate fallback if all keys/configs fail (sandbox mock response)
    const reply = this.getMockResponse("fallback-demo", config.prompt);
    const latencyMs = Date.now() - startTime;
    
    return {
      reply: `[AI Gateway Sandbox Fallback]\n\nAll primary LLM API keys failed or were unconfigured.\nErrors:\n${errorLog.map(e => `- ${e}`).join("\n")}\n\nHere is your fallback response:\n\n${reply}`,
      modelUsed: "sandbox-mock-router",
      costEstimate: 0.0,
      latencyMs
    };
  }

  private static getFallbackChain(requestedModel: string): string[] {
    const defaultChain = ["claude-3-5-sonnet", "gpt-4o", "gemini-1-5-pro", "deepseek-v3"];
    if (defaultChain.includes(requestedModel)) {
      // Prioritize requested model, then fall back to the rest
      return [requestedModel, ...defaultChain.filter(m => m !== requestedModel)];
    }
    return defaultChain;
  }

  private static verifyProviderKey(model: string): boolean {
    if (model.includes("gpt") && process.env.OPENAI_API_KEY && !process.env.OPENAI_API_KEY.startsWith("sk-mock")) return true;
    if (model.includes("claude") && process.env.ANTHROPIC_API_KEY && !process.env.ANTHROPIC_API_KEY.startsWith("sk-ant-mock")) return true;
    if (model.includes("gemini") && process.env.GEMINI_API_KEY && !process.env.GEMINI_API_KEY.startsWith("AIzaSyMock")) return true;
    if (model.includes("deepseek") && process.env.DEEPSEEK_API_KEY && !process.env.DEEPSEEK_API_KEY.startsWith("sk-ds-mock")) return true;
    return false;
  }

  private static calculateCost(model: string, promptChars: number, replyChars: number): number {
    const metrics = COST_METRICS[model] || { prompt: 0, completion: 0 };
    const promptTokens = promptChars / 4;
    const replyTokens = replyChars / 4;
    return (promptTokens * metrics.prompt) + (replyTokens * metrics.completion);
  }

  private static getMockResponse(model: string, prompt: string): string {
    const promptLower = prompt.toLowerCase();
    if (promptLower.includes("docker") || promptLower.includes("compose")) {
      return `To run your monorepo containers, execute:\n\n\`\`\`bash\ndocker-compose up --build -d\n\`\`\`\nThis spins up the database, redis cache, qdrant indexes, next.js app, and runner socket server.`;
    }
    return `This is a high-fidelity response mock generated by the **AiGateway** under the model **${model.toUpperCase()}**.\n\nYou can input real active API keys inside settings to query live provider models.`;
  }
}
